### ISSUE TITLE
[nextcloud] PHP module GD not installed

### ISSUE THREAD

**Issue by Daniel133** [Wonderfall/dockerfiles#119] opened 2017-02-15 14:24 UTC
The new images show this error:

```
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/gd.so' - Error relocating /usr/lib/libpng16.so.16: inflateValidate: symbol not found in Unknown on line 0
PHP module GD not installed.
Please ask your server administrator to install the module.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /nextcloud/lib/private/Console/Application.php:144
Stack trace:

#0 /nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#1 /nextcloud/occ(11): require_once('/nextcloud/cons...')

#2 {main}Trying ownCloud upgrade again to work around ownCloud upgrade bug...
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/gd.so' - Error relocating /usr/lib/libpng16.so.16: inflateValidate: symbol not found in Unknown on line 0
PHP module GD not installed.
Please ask your server administrator to install the module.
```

**Comment by Wonderfall** [comment] 2017-02-15 14:28
Duplicate of https://github.com/Wonderfall/dockerfiles/issues/114
Manual fix : https://github.com/Wonderfall/dockerfiles/issues/114#issuecomment-279971908

**Closed as completed by Wonderfall** 2017-02-15 14:28 UTC
